###
GET http://localhost:3000/matches

###
GET http://localhost:3000/matches/1

###
POST http://localhost:3000/matches
Content-Type: application/json

{
  "away_team": "Manchester United",
  "image_away_team": "https://example.com/manu.png",
  "time": "2026-02-10 19:30",
  "stadium": "Old Trafford",
  "round": "Round 18",
  "season": "2025-2026"
}

###
PATCH http://localhost:3000/matches/1
Content-Type: application/json

{
  "away_team": "Manchester City",
  "image_away_team": "https://example.com/mancity.png",
  "time": "2026-02-17 20:00",
  "stadium": "Etihad Stadium",
  "round": "Round 19",
  "season": "2025-2026"
}

###
DELETE http://localhost:3000/matches/1
